### ISSUE TITLE
Transpile error: Couldn't find preset

### ISSUE THREAD

**Issue by dominik0711** [babel/gulp-babel#101]
Hi. I'm not able to transpile my **es6** code to **es5** due to the following error:

`Couldn't find preset "es2015" relative to directory`
## This is my environment:

OS: OS X 
CLI version 1.2.2  
Local version 4.0.0-alpha.2
## package.json (partial):

```
  "devDependencies": {
    "babel-preset-es2015": "^6.16.0",
    "browser-sync": "^2.7.7",
    "connect-history-api-fallback": "^1.1.0",
    "del": "^2.0.2",
    "es6-promise": "^3.1.2",
    "glob-all": "^3.0.1",
    "gulp": "github:gulpjs/gulp#4.0",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-babel": "^6.1.2",
...
```
## I have the following project structure:

|-!deploy
|-build
|---components
|---helpers
|---node_modules
|---tasks
|-src
|---assets
|---components
|---js
|-----3rd
|-------jspdf
|-------lz-string
|-----ext-store
|-----mod
|---libs
|---style

My gulpfile is inside my **build** folder and from here I would like to transpile my JavaScript (es6) files sitting inside **src/js** folder to my **!deploy** folder.

I have in installed gulpv4, CLI1.2.2, babel-preset-es2015v6.16.0.

Why does gulp-babel reports: 

`Couldn't find preset "es2015" relative to directory "/Users/tester/Projects/XXX/src"`

**Comment by wesww** [comment]
In my build I have to use the full `babel-preset-es2015`. However, I'm using gulp so I don't really know if this is relevant to you. Worth a try though.
```
const babel = require('gulp-babel');

...

.pipe(babel({
  presets: [
    'babel-preset-es2015',
    'babel-preset-stage-2'
  ]
}))
```

**Comment by gucong3000** [comment]
@dominik0711 , Can you help me do a test ?

```bash
npm i gucong3000/babel#patch-1
```
run this command, then try your case.

**Comment by loganfsmyth** [comment]
You should be able to change that to

```
.pipe(babel({
  presets: [
    require('babel-preset-es2015'),
    require('babel-preset-stage-2'),
  ]
}))
```

We expect the presets to be relative to the file being processed, if they are not, you cannot use the string-based preset lookup.

**Comment by trusktr** [comment]
This happens to me with just a plain .babelrc and using the `babel` command, but only when using `npm` v2, not `npm` v4 (haven't tried `npm` v3).

**Comment by trusktr** [comment]
Is the an issues somewhere relating to failures due to differences in npm versions? Haven't found one yet.

**Comment by hzoo** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
