### ISSUE TITLE
gulp using .pipe(babel({presets: [es2015]})) is very slow, one word change takes me 10S. why & how to solve？

### ISSUE THREAD

**Issue by chenghaohao** [babel/gulp-babel#102]

**Comment by loganfsmyth** [comment]
We're going to need more information about your setup.

* Are you on a recent node version?
* Are you on npm v3?
* How many files are you passing to Babel? What is the glob pattern you are using?
* How are you watching for changes? Do you use caching? If you recompile every file any time any file changes, it will be slow.

Give us your whole task.

**Comment by chenghaohao** [comment]
gulp.task('scripts:app', function() {
    log('Building scripts..');
    // Minify and copy all JavaScript (except vendor scripts)
    return gulp.src(source.scripts)
        .pipe($.jsvalidate())
        .on('error', handleError)
        .pipe( $.if( useSourceMaps, $.sourcemaps.init() ))
        .pipe(babel({presets: [es2015]}))
        .pipe($.concat( 'app.js' ))
        .pipe($.ngAnnotate())      
        .on('error', handleError)
        .pipe( $.if(isProduction, $.uglify({preserveComments:'some'}) ))
        .on('error', handleError)
        .pipe( $.if( useSourceMaps, $.sourcemaps.write() ))
        .pipe(gulp.dest(build.scripts))
});

just like this..

**Comment by loganfsmyth** [comment]
You didn't answer my other questions. Please do. You also probably want to use https://www.npmjs.com/package/gulp-watch since presumable you rerun `scripts:app` fully at the moment, which means you process every file whenever _any_ file changes.

**Comment by hzoo** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
