### ISSUE TITLE
Option 'ignore' isn't working

### ISSUE THREAD

**Issue by stevenwright1243** [babel/gulp-babel#106]
``` js
var jsArray = [
  'development/js/colors.js',
  'development/js/scripts.js',
];

var babelIgnore = [
  'development/js/scripts.js',
];

gulp.task('javascript', function() {
  return gulp.src(jsArray, { base: 'development/js' })
  .pipe(babel({
    presets: ['latest'],
    ignore: babelIgnore
  }))
   /* other tasks */
  .pipe(gulp.dest(dest));
}); 
```

The scripts.js file continues to get run through the babel task...

I also tried this
`ignore: ['development/js/**/**.js']`
but everything was still being ran through babel...

Is there something I'm doing wrong? Can't find guidance on this anywhere so I made an issue.

Relevant package versions
"babel-preset-latest": "^6.22.0"
"gulp": "^3.9.1"
"gulp-babel": "^6.1.2"

Node version 7.4.0

Windows 10

**Comment by stevenwright1243** [comment]
If it helps anyone, I ended up using the 'only' option and getting the difference of both arrays to effectively accomplish what 'ignore' does.

```js
const jsArray = [
  'development/js/libs/jquery.js',
  'development/js/libs/fullpage.js',
  'development/js/libs/parallax.js',
  'development/js/parallax.js',
  'development/js/libs/anime.js',
  'development/js/anime.js',
  'development/js/libs/shine.js',
  'development/js/shine.js',
  'development/js/colors.js',
  'development/js/scripts.js',
];

const babelIgnore = [
  'development/js/libs/anime.js',
];

const usableBabelIgnore = jsArray.filter(x => babelIgnore.indexOf(x) < 0);

gulp.task('javascript', () => {
  return gulp.src(jsArray, { base: 'development/js' })
  .pipe(babel({
    presets: ['latest'],
    only: usableBabelIgnore,
  }))
  .pipe(gulp.dest(`${limbo}js`));
});
```

**Comment by hzoo** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).

**Comment by pawelsas** [comment]
Same issue over here.
Neither "ignore" nor "only" is working for me.

`var srcFiles = [
    `${global.paths.src}/js/jquery.slim.min.js`,
    `${global.paths.src}/js/plugins/**`,
    `${global.paths.src}/js/components/**`,
    `${global.paths.src}/js/pages/**`,
    `${global.paths.src}/js/main.js`
];

var srcPlugins = [
    `${global.paths.src}/js/jquery.slim.min.js`,
    `${global.paths.src}/js/plugins/**`
];

gulp.task('scripts', () => {
    gulp.src(srcFiles)
        .pipe(buffer())
        .pipe(sourcemaps.init())
        .pipe(babel({
            ignore: srcPlugins,
            presets: ['es2015']
        }))
        .pipe(concat('script.js'))
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest(global.paths.src));
});`

**Comment by loganfsmyth** [comment]
`ignore` is notoriously bad in Babel 6. If you want you can try passing a function instead and doing the glob matching yourself. I doubt there is much `babel-gulp` could do to fix this though.

In Babel 7's Beta I believe this code is much more likely to work.

**Comment by pawelsas** [comment]
It works in .babelrc file.

**Comment by geonanorch** [comment]
Just wanted to mention that I am having the reverse issue; with gulp-babel v8.0.0.beta2:
* in `.babelrc` top-level entries like `ignore` are ignored (no pun intended); but `presets` is used
* passing the same `ignore` entry directly in the `.pipe(babel({ . . . }))` call works

However if I provide configuration with `babel(myconfig)`, then `.babelrc` is not longer used.
(suggest to describe that behavior in README, I guess the topic of #114)

My current solution is to pass everything in a config object and remove the `.babelrc` file
--which means that I cannot share the configuration with other babel clients...

**Comment by loganfsmyth** [comment]
I'm triaging old issues on gulp-babel. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.

**Comment by lili21** [comment]
Still doesn't work. I'm using babel@7.2.2 and gulp-babel@8.0.0

**Comment by lili21** [comment]
work around: Using `gulp.src(..., { ignore: [...] }`

**Comment by morganney** [comment]
As a workaround you can just use the `ignore` option for `gulp.src`.
