### ISSUE TITLE
gulp error received after upgrade babel-preset-react to 6.23.0

### ISSUE THREAD

**Issue by achmadk** [babel/gulp-babel#107]
I have upgraded babel-preset-react dependency to version 6.23.0. When I run `gulp` in my project with upgraded version of babel-preset-react, I got error like this
```javascript
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:695:5)
    at [MY_PROJECT_DIRECTORY]\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:353:36
    at [MY_PROJECT_DIRECTORY]\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:375:22
    at Array.map (native)
    at OptionManager.resolvePresets ([MY_PROJECT_DIRECTORY]\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:364:20)
    at OptionManager.mergePresets ([MY_PROJECT_DIRECTORY]\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:348:10)
    at OptionManager.mergeOptions ([MY_PROJECT_DIRECTORY]\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:307:14)
    at [MY_PROJECT_DIRECTORY]\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:349:14
    at [MY_PROJECT_DIRECTORY]\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:369:24
```
This error is gone when I downgrade babel-preset-react version to 6.22.0.

**Comment by loganfsmyth** [comment]
What version of `gulp-babel` are you using?

**Comment by achmadk** [comment]
I'am using `gulp-babel` version 6.1.2, Mr. @loganfsmyth .

**Comment by loganfsmyth** [comment]
Can you check the `version` value in `[MY_PROJECT_DIRECTORY]\node_modules\gulp-babel\node_modules\babel-core\package.json`? That error could happen on older versions of `babel-core` but I was under the impression that this had been fixed long ago.

**Comment by achmadk** [comment]
Yes, I can, Mr. @loganfsmyth . The `babel-core` version inside `gulp-babel` module is version 6.7.4.

**Comment by loganfsmyth** [comment]
That is an extremely old version of `babel-core`. I'm not sure why you'd have an old version. I'd recommend clearing and reinstalling your deps, and potentially looking at your package.json to make sure you haven't somehow locked it to an old version. `gulp-babel` is set with a very generic `>=6.0.2` so it will install the most recent version of 6.x possible.

**Comment by hzoo** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
