### ISSUE TITLE
Option for asking babel to not clean destination directory

### ISSUE THREAD

**Issue by saketh-bobby** [babel/gulp-babel#116]
Correct me if I'm wrong ! I'm using babel and nodemon in my workflow such that gulp-babel watches src directory and whenever file changes it transpiles to dest directory and nodemon watches the dest directory for restarting the server. 

The problem is babel is correctly transpiling the target file but nodemon is restarting cuz of change for  n number of times where n is number of files in dest directory but I need it to restart only once since 1 file is changed.

What I understand from this anamoly is,  babel is cleaning the dest directory and mapping src file to dest directory and also since there is no change in remaining files filling the dest directory with them again.So nodemon thinks n numbere of files changed  and restarts n number of times.

 Is the above case is what's really happening ? If that's the case is there an option not to clean directory for not changed files ? Hope this makes sense

**Comment by loganfsmyth** [comment]
This isn't really the responsibility of gulp-babel. You could use so.ething like gulp-cached to only process files that change for instance.

**Comment by saketh-bobby** [comment]
Oh thanks it'll work !
