### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by matfin** [babel/gulp-babel#117]
Hi,

I am experimenting with ES7 generators in my project. I followed these instructions [https://www.npmjs.com/package/gulp-babel#runtime](https://www.npmjs.com/package/gulp-babel#runtime) to install the required gulp-babel plugin.

I am seeing an error in my console as follows when I reload the page:
```
main.js:3 Uncaught ReferenceError: require is not defined
```

Inside `main.js:3` there is the line:
```
var _promise = require('babel-runtime/core-js/promise');
```

The task within my `gulpfile.js` looks like this: 
```
gulp.task('scripts-dev', () => {
	return gulp
	.src('./assets/scripts/**/*')
	.pipe(jshint())
	.pipe(jshint.reporter('default'))
	.pipe(concat('main.js'))
	.pipe(babel({
		presets: ['es2015'],
		plugins: ['transform-runtime']
	}))
	.pipe(gulp.dest(dest.scripts));
});
```

Is there another plugin I need to install to get this working? 

For reference, the branch I am experimenting with for my project can be seen [here](https://github.com/matfin/mattfinucane.com/tree/feature/generators).

**Comment by rationality6** [comment]
Same error here. 

Do I need to learnd about requirejs or something?

**Comment by mlankenau** [comment]
I get the same error

**Comment by hzoo** [comment]
The `require` identifier/function is undefined since it's not in the browser. You need to run your code through a bundler like https://webpack.js.org which will handle that. If you still need to use gulp, there's https://www.npmjs.com/package/gulp-webpack

**Comment by matfin** [comment]
Thanks. I will take a look. Can I suggest an update to the [documentation](https://www.npmjs.com/package/gulp-babel#runtime) to include the info above?

**Comment by rationality6** [comment]
I solved this error with this way. 
change babel to latest preset.
I read babel documentations

https://github.com/babel/babel-preset-env


.pipe(babel({
      presets: ['env']
    }))

and than install babel polyfill

and gonna eveyrhings work fine.

**Comment by martinkovac** [comment]
@rationality6 it doesn't work for me. It works when you remove plugins: ['transform-runtime'].

**Comment by loganfsmyth** [comment]
`transform-runtime` is by definition modular. If you're using it, you need to be using your code in an environment that supports modules, so either Node or client-side with Webpack or Browserify.
