### ISSUE TITLE
Add ability to ignore files with specified name to go through babel transform

### ISSUE THREAD

**Issue by mxshrestha** [babel/gulp-babel#118]
there are cases where files need to be bypassed through babel transform. For example: https://github.com/lodash/babel-plugin-lodash/issues/83

```
.transform(function(filename, opts) {
  if (require.resolve("in-view") === filename) {
    return new require("stream").PassThrough();
  }
  return require("babelify")(filename, opts);
}, { global:true, presets:["es2015"] })
```

**Comment by loganfsmyth** [comment]
I'm triaging old issues on gulp-babel. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.

This appears to be an issue with `babelify` anyway.
