### ISSUE TITLE
presets: ['env'] being ignored

### ISSUE THREAD

**Issue by zhawkins** [babel/gulp-babel#125]
I found a weird bug (maybe?) and I thought I'd submit it as an issue in case others are having similar problems.

Gulp setup like so:
```
.pipe(
  babel({ presets: ['env'] })
    .on('error', handleError)
)
```

My babel config within `package.json` seems to be ignored.
```
"babel": {
  "presets": [
    ["env", {
      "targets": {
        "chrome": 54
      }
    }]
  ]
}
```

However once I update Gulp with:
```
.pipe(
  babel()
    .on('error', handleError)
)
```
the env config works. ¯\_(ツ)_/¯

Still not sure if it's a bug or a mistake on my part.

**Comment by nmiddendorff** [comment]
I would check your package.json to see if babel settings are defined there. The presets in package.json may override the settings you fed to the babel function in Gulp.

**Comment by WuglyakBolgoink** [comment]
@zhawkins & @nmiddendorff 

Preset **`env`** was again renamed into **`@babel/preset-env`**.

Be sure to have this new packages in **`package.json`**:
```
        "@babel/cli": "^7.0.0-beta.41",
        "@babel/core": "^7.0.0-beta.41",
        "@babel/preset-env": "^7.0.0-beta.41",
```

**Comment by hzoo** [comment]
@WuglyakBolgoink That's only for Babel 7, the issue is old so it's probably unrelated since the OP didn't specify the version.
