### ISSUE TITLE
TypeError: Cannot read property 'transform' of undefined

### ISSUE THREAD

**Issue by realisation** [babel/gulp-babel#126]
I followed the directions on the babejs.io page to the T, but I'm getting a problem here that 'default' on _babelCore2 is not defined. 

This is my transpiled code: 

```
  1 'use strict';
  2 
  3 var _babylon = require('babylon');
  4 
  5 var babylon = _interopRequireWildcard(_babylon);
  6 
  7 var _fs = require('fs');
  8 
  9 var _fs2 = _interopRequireDefault(_fs);
 10 
 11 var _babelCore = require('babel-core');
 12 
 13 var _babelCore2 = _interopRequireDefault(_babelCore);
 14 
 15 var _visitor = require('./visitor');
 16 
 17 var _visitor2 = _interopRequireDefault(_visitor);
 18 
 19 function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj :     { default: obj }; }
 20 
 21 function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return     obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if     (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key]; } }     newObj.default = obj; return newObj; } }
 22 
 23 _fs2.default.readFile(process.argv[2], function (err, data) {
 24   var src = data.toString();
 25   var out = _babelCore2.default.transform(src, {
 26     plugins: [_visitor2.default]
 27   });
 28   // console.log(out.code)
 29 });
```

I have the 'env' preset activated in my .babelrc. What's up with that?

**Comment by loganfsmyth** [comment]
It's possible the docs are out of date. Which instructions are you following?

It looks like you're doing

    import babel from "babel-core";
    babel.transform()

instead of

    import {transform} from "babel-core";
    transform();

**Comment by realisation** [comment]
It looks like __esModule is true, and therefore it isn't cast into an object under the `default` key.
Yes, hmmm, when I manually set _babelCore.__esModule to false, it works.

**Comment by loganfsmyth** [comment]
Well don't do that :P We just don't export the interface such that `import babel from "babel-core";` works, if you want to use `babel.transform`, you should do `import * as babel from "babel-core";`.

**Comment by realisation** [comment]
Hmm - I'm a little confused, I didn't write any of that code; that code is the transpiled code.

**Comment by loganfsmyth** [comment]
You showed your compiled code, but what does your original uncompiled code look like? It's an issue with that.

**Comment by realisation** [comment]
I know! sorry I am eating my shoe here

**Comment by realisation** [comment]
Let's rewind to your second comment

**Comment by realisation** [comment]
Looks like your suggestion works. I wonder why - now it's not making a _babelCore2

**Comment by realisation** [comment]
Thanks :)
