### ISSUE TITLE
Specify .babelrc

### ISSUE THREAD

**Issue by kyleholzinger** [babel/gulp-babel#127]
Can you specify your own `.babelrc` file? I want to have a different preset in development vs in production. (I develop in chrome, but I need to be able to target back to IE11)

**Comment by ben-z** [comment]
I think this is a duplicate of #48.

**Comment by iDVB** [comment]
@Sawtaytoes why is there an issue that says it does? 
https://github.com/babel/gulp-babel/issues/48

**Comment by hzoo** [comment]
Not sure what this is asking for, gulp-babel will read the babelrc in your project yes.

**Comment by kyleholzinger** [comment]
Wasn't aware of the `env` config flag. Thank you very much @hzoo !
