### ISSUE TITLE
[bug?] Seems to minify output by default, but I haven't specified that.

### ISSUE THREAD

**Issue by trusktr** [babel/gulp-babel#129]
I've got a gulpfile:

```js
const gulp = require('gulp')
const rollup = require('rollup-stream')
const source = require('vinyl-source-stream')
const rollupConfig = require('./rollup.config')

// using gulp-better-rollup
gulp.task('build-global', () =>
    rollup(rollupConfig)
        .pipe(source('global.js'))
        .pipe(gulp.dest('global.js'))
)
```

The output is not minified.

Then when I add gulp-babel:

```js
const gulp = require('gulp')
const babel = require('gulp-babel')
const rollup = require('rollup-stream')
const source = require('vinyl-source-stream')
const rollupConfig = require('./rollup.config')

// using gulp-better-rollup
gulp.task('build-global', () =>
    rollup(rollupConfig)
        .pipe(source('global.js'))
        .pipe(babel({
            plugins: [
                'transform-es2015-shorthand-properties'
            ],
        }))
        // TODO source maps
        .pipe(gulp.dest('global.js'))
)
```

it will minify the output.

My babel.config looks like this:

```js
module.exports = {
    plugins: [
        ['transform-builtin-classes', { globals: ['HTMLElement'] }],
        'transform-es2015-classes',
        'transform-object-rest-spread',
        'array-includes',
        ['transform-runtime', {
            helpers: true,
            polyfill: true,
            regenerator: false,
        }],
    ],
}
```

So I don't see why it is minifying stuff without me specifying that (I don't want it to minify).

**Comment by loganfsmyth** [comment]
> it will minify the output.

What output? You haven't given any examples.

**Comment by loganfsmyth** [comment]
Chances are it is printing this message: https://github.com/babel/babel/blob/master/packages/babel-generator/src/index.js#L76

So pass `compact: false` if you don't want that. Generally you'd run Babel via Rollup instead of via Gulp though, since processing the individual files is much more flexible. What you have now passes Babel the whole large bundle that Rollup outputs.

**Comment by loganfsmyth** [comment]
Also, as I'm sure we've mentioned in issues in the past that you've filed, unless you're totally sure something is a bug, we generally direct support questions away from Github: https://github.com/babel/babel#looking-for-support

**Comment by trusktr** [comment]
> What you have now passes Babel the whole large bundle that Rollup outputs.

True, I was trying to change Rollup's module output, which is not configurable in Rollup.

I was seeing that "deoptimized" message. It just shouldn't be on by default. (is that considered a bug?)

I don't need this anymore but thanks for the tip anyways.
