### ISSUE TITLE
babel-core is missing in npm readme.

### ISSUE THREAD

**Issue by godtail** [babel/gulp-babel#132]
`$ npm install --save-dev gulp-babel babel-preset-env`
> missing package babel-core, link: https://www.npmjs.com/package/gulp-babel

**Comment by zalog** [comment]
To solve this we can switch to:
```
"@babel/core": "7.0.0-beta.34"
"gulp-babel": **"8.0.0-beta.0"**
```
But still :)

**Comment by loganfsmyth** [comment]
`gulp-babel` has a peer dependency on `babel-core` so generally you'll want to `npm install gulp-babel babel-core babel-preset-env` to get them all set. Looks like the documentation is stale, sorry about that.

**Comment by zalog** [comment]
cc #123
