### ISSUE TITLE
gulpjs recommends upgrading of vinyl for dependent plugins due to issues with gulp 4.0.0-alpha.3

### ISSUE THREAD

**Issue by dozer75** [babel/gulp-babel#136]
Refer to gulpjs/gulp#2065 @phated recommend upgrading usage of vinyl to 2.0 or 2.1 and to stop using gulp-util. I can see that your project is using gulp-util and thus an old vinyl that  they says isn't compatible with gulp 4.0.0.

For further discussions I think it's better that you take it directly with the @gulpjs project since I don't know whats exactly is the problem.

**Comment by phated** [comment]
Ref #137

**Comment by phated** [comment]
ping @hzoo

**Comment by demurgos** [comment]
Closed by #127.
