### ISSUE TITLE
Spread operator not recognized in object declaration

### ISSUE THREAD

**Issue by wscourge** [babel/gulp-babel#142]
Minimal example:

*gulpfile.js*
```javascript
const gulp = require('gulp');
const concat = require('gulp-concat');
const babel = require('gulp-babel');

gulp.task('nope', () => {

  return gulp
    .src('./nope.js')
    .pipe(babel({ presets: ['env'] })
    .pipe(gulp.dest('transpiled');

});
```

*nope.js*
```javascript
const y = Math.random() > 0.5;
let x = {
  q: 1,
  ... y && { a: 2 }
}
```

Running `gulp nope` produces following error:

> throw er; // Unhandled 'error' event
      ^
SyntaxError: /directory/nope.js: Unexpected token (7:4)
&nbsp;&nbsp;&nbsp;&nbsp;5  | let x = {
&nbsp;&nbsp;&nbsp;&nbsp;6 |&nbsp;&nbsp;q: 1,
&nbsp;> 7 |&nbsp;&nbsp;... y && { a: 2 }
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;^
&nbsp;&nbsp;&nbsp;&nbsp;8  | }
&nbsp;&nbsp;&nbsp;&nbsp;9  | 
&nbsp;&nbsp;&nbsp;&nbsp;at Parser.pp$5.raise (/directory/node_modules/babylon/lib/index.js:4454:13)
&nbsp;&nbsp;&nbsp;&nbsp;at Parser.pp.unexpected (/directory/node_modules/babylon/lib/index.js:1761:8)
&nbsp;&nbsp;&nbsp;&nbsp;at Parser.pp$3.parseIdentifier (/directory/node_modules/babylon/lib/index.js:4332:10)
&nbsp;&nbsp;&nbsp;&nbsp;at Parser.pp$3.parsePropertyName (/directory/node_modules/babylon/lib/index.js:4156:96)
&nbsp;&nbsp;&nbsp;&nbsp;at Parser.pp$3.parseObj (/directory/node_modules/babylon/lib/index.js:4045:12)
&nbsp;&nbsp;&nbsp;&nbsp;at Parser.pp$3.parseExprAtom (/directory/node_modules/babylon/lib/index.js:3719:19)
&nbsp;&nbsp;&nbsp;&nbsp;at Parser.pp$3.parseExprSubscripts (/directory/node_modules/babylon/lib/index.js:3494:19)
&nbsp;&nbsp;&nbsp;&nbsp;at Parser.pp$3.parseMaybeUnary (/directory/node_modules/babylon/lib/index.js:3474:19)
&nbsp;&nbsp;&nbsp;&nbsp;at Parser.pp$3.parseExprOps (/directory/node_modules/babylon/lib/index.js:3404:19)
&nbsp;&nbsp;&nbsp;&nbsp;at Parser.pp$3.parseMaybeConditional (/directory/node_modules/babylon/lib/index.js:3381:19)

*My environment*:

`node -v` v8.5.0
`npm -v` 5.5.1

*package.json.dependencies*
```javascript
"dependencies": {
  "babel-core": "^6.26.0",
  "babel-preset-env": "^1.6.1",
  "gulp": "^3.9.1",
  "gulp-babel": "^7.0.0"
}
```

I created [example](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYewdgzgLgBARiEAbGBeGBZAhlAFgOgCcswATEAWwAoBKGAPhgAZ8BWAbgCgkBTWADzQwA3pwCQARwBcMAIwAaTjBj5V8RCgBkmkTACeMgEwBfTsaA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=) on https://babeljs.io/repl.

**Comment by loganfsmyth** [comment]
You are missing https://babeljs.io/docs/plugins/transform-object-rest-spread/. Spread in objects is not a standard feature yet.

**Comment by sasilver75** [comment]
> You are missing https://babeljs.io/docs/plugins/transform-object-rest-spread/. Spread in objects is not a standard feature yet.

This makes me very sad

can you




implement it

**Comment by ilikebuttons** [comment]
This is what did it for me:

`npm install --save-dev babel-plugin-transform-object-rest-spread`

Then, in package.json, I added the following babel configuration:

```
"babel": {
    "plugins": [
      "transform-object-rest-spread"
    ]
  }
```
