### ISSUE TITLE
[gulp-babel@7.0.1] ReferenceError: Using removed Babel 6 option: .sourceMapTarget

### ISSUE THREAD

**Issue by etnbrd** [babel/gulp-babel#152]
When using gulp with this gulpfile.babel.js:
```
import gulp from 'gulp';
import babel from 'gulp-babel';

gulp.task('default', function() {
  return gulp
    .src('src/**/*.js')
    .pipe(babel())
    .pipe(gulp.dest('dist'));
})
```
With these versions:
```
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.44",
    "@babel/preset-env": "^7.0.0-beta.44",
    "gulp": "^3.9.1",
    "gulp-babel": "^7.0.1"
  },
```
I get this error:
ReferenceError: Using removed Babel 6 option: .sourceMapTarget - The `sourceMapTarget` option has been removed because it makes more sense for the tooling that calls Babel to assign `map.file` themselves.

I fixed it inside my own node_modules, by removing the offending line ([index.js:33](https://github.com/babel/gulp-babel/blob/v7-maintenance/index.js#L33)).

Should this option be removed entirely or did I miss something ?

**Comment by loganfsmyth** [comment]
```
"gulp-babel": "^7.0.1"
```
is for Babel 6. If you're using Babel 7 you need to be using `8.0.0-beta.2`

**Comment by Wxh16144** [comment]
> ```
> "gulp-babel": "^7.0.1"
> ```
> 
> 适用于Babel 6.如果您使用的是Babel 7，则需要使用 `8.0.0-beta.2`

Thank you ever so much, Solved the headache of the day;

**Comment by EBEREGIT** [comment]
> > ```
> > "gulp-babel": "^7.0.1"
> > ```
> > 
> > 
> > 适用于Babel 6.如果您使用的是Babel 7，则需要使用 `8.0.0-beta.2`
> 
> Thank you ever so much, Solved the headache of the day;

How exactly did you solve the problem? Can you list the steps?

**Comment by EBEREGIT** [comment]
> ```
> "gulp-babel": "^7.0.1"
> ```
> 
> is for Babel 6. If you're using Babel 7 you need to be using `8.0.0-beta.2`

Please explain the steps to solve this issue. I don't understand

**Comment by EBEREGIT** [comment]
yaayh... I solved it. I ran the following code and everything runs properly

`npm install gulp-babel@8.0.0`
