### ISSUE TITLE
Using @babel/preset-typescript, unsure how to include .ts and .tsx file extensions with gulp-babel

### ISSUE THREAD

**Issue by chrisgervang** [babel/gulp-babel#153]
Hi there,

I'm trying to use typescript with babel, and I use gulp. I'm aware of the issue surrounding the .ts and .tsx file extension babel issues (https://github.com/babel/babel/pull/6027), and the recommended solution to put this somewhere, but I'm not sure where it goes when using gulp-babel:

```
require('@babel/register', {
  extensions: ['.js', '.jsx', '.ts', '.tsx']
})
```

This code might need to be added to gulp-babel in order to register the extensions correctly, since none of my project's code executes as it is being built, and running it in my gulp task didn't work. I also tried passing an `extensions` option into gulp-babel, but that returned an error:
```
ReferenceError in plugin "gulp-babel"
Message:
    Unknown option: .extensions. Check out http://babeljs.io/docs/usage/options/ for more information about options.
```

**Comment by chrisgervang** [comment]
@hzoo is there anything I can do to help with this, or do you have time to look into this? Although the upstream change that could fix this (babel/babel#6027) isn't implemented, other downstream tools like babelify have work arounds. I was wondering, do you know something that could work for gulp?

**Comment by loganfsmyth** [comment]
@chrisgervang Could you clarify exactly what issue you're currently running into with `gulp-babel`? It should just process any file given to it based on what you list in `gulp.src`, so Babel itself doesn't really need to know what extensions are in use in `gulp-babel`'s case.

Are we talking about when you are compiling your files, or when you try to run them? What specific issues are you seeing in a normal configuration?

**Comment by chrisgervang** [comment]
@loganfsmyth this issue occurs while compiling files. The issue might be that `gulp.src` isn't including any `.ts`, `.tsx` in it's search for some reason.

**Comment by loganfsmyth** [comment]
Without seeing your Gulp task, it is hard to say. Could you add more code?

**Comment by chrisgervang** [comment]
After changing `gulp.src` to a list of string file globs that includes `.ts` and `.tsx` files, the issue was fixed. Thanks for the guidance!
