### ISSUE TITLE
How set the stage-2

### ISSUE THREAD

**Issue by ad-git** [babel/gulp-babel#155]
There is any way to set the level stage-2. I try this but dont work

```
"presets": [
                ["env", {
                  "targets": {
                    "chrome": 52
                  }
                }],
                "stage-2"
              ]
```

**Comment by loganfsmyth** [comment]
Please elaborate on "doesn't work". That is the correct way to do it. Maybe you forgot to install it?

**Comment by ad-git** [comment]
Ok "i elaborate" that your answer is not useful at all, so resolve it alone. 

Thx you for your time any way
