### ISSUE TITLE
crash on error

### ISSUE THREAD

**Issue by yukulele** [babel/gulp-babel#16]
gulp-babel make gulp crash when their is an error on source

my source:

    var i = 5:

error:

    [15:50:28] Starting 'babel'...
    [15:50:28] Finished 'babel' after 111 ms

    events.js:125
          throw er; // Unhandled 'error' event
                ^
    SyntaxError: C:/wamp/www/src/js/test.js: Unexpected token (1:9)
    > 1  | ←[36mvar←[39m ←[37ma←[39m ←[1m←[37m=←[39m←[22m ←[35m5←[39m←[1m←[37m:←[39m←[22m

**Comment by sebmck** [comment]
Yep, you need to add an `error` handler to your gulpfile. If you post your gulpfile.js I can show you what to put and where to put it.

**Comment by yukulele** [comment]
my `gulpfile.js`:
```javascript
var gulp = require("gulp");
var babel = require('gulp-babel');
var sourcemaps = require('gulp-sourcemaps');

gulp.task("default", function(){
  gulp.watch("src/js/**/*.js", ["babel"]);
});

gulp.task("babel", function(){
  gulp.src("src/js/**/*.js")
    .pipe(sourcemaps.init())
    .pipe(babel())
    .pipe(gulp.dest("www/js/"));
});
```

**Comment by sindresorhus** [comment]
```js
var gulp = require("gulp");
var babel = require('gulp-babel');
var sourcemaps = require('gulp-sourcemaps');

gulp.task("default", function(){
  gulp.watch("src/js/**/*.js", ["babel"]);
});

gulp.task("babel", function(){
  gulp.src("src/js/**/*.js")
    .pipe(sourcemaps.init())
    .pipe(babel())
    .on('error', console.error.bind(console));
    .pipe(gulp.dest("www/js/"));
});
```

This is how all gulp plugins works and nothing specific to this one.

**Comment by PinkaminaDianePie** [comment]
Does not help for me.
case:
compiling my files with this code:

	return gulp.src(paths.jsServer.concat(paths.serverExclude))
		.pipe(insert.prepend('require("source-map-support").install();require("babel/polyfill");'))
		.pipe(sourcemaps.init())
		.pipe(babel())
		.on('error', console.error.bind(console))
		.pipe(sourcemaps.write('.'))
		.pipe(gulp.dest(paths.dest+'server/build'));

if syntax error thrown gulp does not crash, but after i fix my code file does not recompile. it goes to dest without changes. other files does not recompile too. watchers works fine, but all files goes to dest without changes

**Comment by kevinb7** [comment]
@PinkaminaDianePie I ran into the same issue.  I ended up modifying the plugin so that it doesn't `emit` an error.  Instead it just logs the error.  This allows the babel to continue running after you fix the syntax error.

gulp-babel/index.js (before):
```
    } catch (err) {
        this.emit('error', new gutil.PluginError('gulp-babel', err, {fileName: file.path, showProperties: false}));
    }
```
gulp-babel/index.js (after):
```
    } catch (err) {
        console.log("[Babel] Syntax Error: " + file.path);
        console.log(err.codeFrame);
    }
```

**Comment by darkbaby123** [comment]
I found there's no need to modify the plugin. Just add `this.emit('end')` on error handler and it works.

Below is my whole task:

```js
gulp.task('babel', ['babelPolyfill'], function(done) {
  gulp.src(paths.js)
    .pipe(sourcemaps.init())
    .pipe(babel())
    .on('error', function(e) {
      console.log('>>> ERROR', e);
      // emit here
      this.emit('end');
    })
    .pipe(concat('all.js'))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('./www/app/'))
    .on('end', done);
});
```

**Comment by octref** [comment]
The method originally posted by @sindresorhus doesn't work if you are watching for recompilation. After a compilation error the watch will not keep recompiling even if you fixed your code.

`gulp-plumber` solves the problem for me:

```js
gulp.task('babel', () => {
  return gulp.src('src/**/*.js')
    .pipe(plumber())
    .pipe(babel({
      presets: ['es2015']
    }))
    .on('error', (err) => {
      gutil.log(gutil.colors.red('[Compilation Error]'));
      gutil.log(gutil.colors.red(err.message));
    })
    .pipe(gulp.dest('dist'));
});

```

**Comment by jdoubleu** [comment]
Okay, a bit too late but I fixed it very simple.

My goal was to get the same environment with gulp-babel as gulp-sass has.

It's a mixing of some answer and you don't need any other module (like `gulp-plumber`):
```
    ...
    .pipe(babel())
    .on('error', function(e) {
      console.error(e);
      this.emit('end');
    })
    .pipe(gulp.dest('./www/app/'));
    ...
```
This will show up an big, red error in the console if your es6 is incorrect but will not break the gulp task.

**Comment by xthilakx** [comment]
@jdoubleu Thanks.. it worked great. Although I had to do a bit of head scratching because I was using an arrow function, and `this` doesn't point to right execution context, if you are using arrow functions.

**Comment by moxx** [comment]
Just for google searcher:

the ES6 lambda syntax `(err) => {}` dose not work because lambda has no `this` scope, so instead use closure.

A fine solution with maximum Error Output will be:
```js
return gulp.src(['./src/app/**/*.js'])
        .pipe(babel({
            presets: ['es2015', 'es2016']
        }).on('error', function(err) {
          // For gulp-util users u can use a more colorfull variation
          // util.log(util.colors.red('[Compilation Error]'));
          // util.log(err.fileName + ( err.loc ? `( ${err.loc.line}, ${err.loc.column} ): ` : ': '));
          // util.log(util.colors.red('error Babel: ' + err.message + '\n'));
          // util.log(err.codeFrame);

          console.log('[Compilation Error]');
          console.log(err.fileName + ( err.loc ? `( ${err.loc.line}, ${err.loc.column} ): ` : ': '));
          console.log('error Babel: ' + err.message + '\n');
          console.log(err.codeFrame);

          this.emit('end');
        }))
        .pipe(gulp.dest(`./${config.dir}/app`))
```

**Comment by leotm** [comment]
I lost just over an hour, due to a trailing comma, in my parent folders' package.json (not sure why Babel is even checking there).
It was showing:
```
events.js
throw er; // Unhandled 'error' event
SyntaxError: path/to/parent/package.json: Error while parsing JSON - Unexpected token } in JSON at position
```
