### ISSUE TITLE
is gulp-babel using .babelrc file?

### ISSUE THREAD

**Issue by bmy4415** [babel/gulp-babel#160]
Hello, I am new to gulp and gulp-babel.
I used `node: v8.9.4` and I wanted to use `async/await` and `import/export`. So I used gulp and gulp-babel plugin.
At first I made `gulpfile.babel.js` like below.
```
// apply babel
gulp.task('build', () => {
	gulp.src(SRC.APP)
		.pipe(babel({
			presets: ['es2017'],
		}))
		.pipe(gulp.dest(DEST.APP));
});
```

But every time I build, it generates `regeneratorRuntime` and I cannot run my program using node.
I tried many solutions like `babel-plugin-transform-runtime`, but the result was same.

Strangely,  after I changed my `.babelrc` everything works well. It did not generate `regeneratorRuntime`. 
I thought that gulp will only use gulpfile configuration to do task, but it seems that it use another environment(in my case, `.babelrc` file).

Can anyone explain about this ?

**Comment by loganfsmyth** [comment]
Yes, `gulp-babel` will use Babel config files. You can pass `babelrc: false` if you'd like to disable that.

**Comment by bmy4415** [comment]
Thanks @loganfsmyth .
Then, when I specify babel options at `gulpfile.babel.js` and I already have .babeljs, will config on `gulpfile.babel.js` be ignored?

**Comment by loganfsmyth** [comment]
Yes, though personally I don't use `gulpfile.babel.js`, I'd use `gulpfile.js` and just only use features available on node.

**Comment by bmy4415** [comment]
Thanks. I used `gulpfile.babel.js` to use `import/export`(which is not supported at my node version).
Thanks to you, I can understand what happen.
