### ISSUE TITLE
Add support for @babel/preset-env instead of babel-preset-env

### ISSUE THREAD

**Issue by bugejakurt** [babel/gulp-babel#161]
In gulp-babel I receive "Cannot find module 'babel-preset-env'" with gulp-babel 8.0.0-beta.2

**Comment by allanjackson** [comment]
I'm having this same issue with the final version 8.0.0

**Comment by loganfsmyth** [comment]
`8.0.0` is for use with Babel 7.x. With Babel 7 you'd be using `@babel/preset-env`. If you're using Babel 6.x and `babel-preset-env` you should use `gulp-babel@7`.

**Comment by loganfsmyth** [comment]
@bugejakurt I can't actually tell what issue you're seeing. If Babel is saying

> Cannot find module 'babel-preset-env'

it probably means that your own config file for Babel is referencing the wrong preset.

**Comment by bugejakurt** [comment]
@loganfsmyth Thanks, this solved my issue: https://github.com/babel/babel-loader/issues/616
