### ISSUE TITLE
gulp-babel@8 babel@7 can not transform jsx to js

### ISSUE THREAD

**Issue by zengkan0703** [babel/gulp-babel#168]
Hello，I have some problem when I update babel and gulp-babel to the latest, I can`t transform jsx to js.

This is my gulpfile.js:
```javascript
const gulp        = require('gulp');
const babel       = require('gulp-babel');
const sass        = require('gulp-sass');
const sourcemaps  = require('gulp-sourcemaps');
...
gulp.task('bable', function(){
  return gulp.src(['./src/**/*.js', './src/**/*.jsx'])
    .pipe(babel())
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('dist'))
});
...
gulp.task('default', ['bable', ...]);
```
This is my package.json:

```javascript
...
 "@babel/core": "^7.1.5",
    "@babel/plugin-proposal-export-default-from": "^7.0.0",
    "@babel/plugin-syntax-export-default-from": "^7.0.0",
    "@babel/plugin-transform-react-jsx": "^7.0.0",
    "@babel/preset-env": "^7.1.5",
    "@babel/preset-react": "^7.0.0",
    "gulp-babel": "^8.0.0",
    "babel-eslint": "^7.2.3",
    "babel-loader": "^8.0.4",
...
```
This is my .babelrc:
```javascript
 {
	"presets": ["@babel/preset-env", "@babel/preset-react"],
	"plugins": [
		"@babel/plugin-syntax-export-default-from",
		"@babel/plugin-proposal-export-default-from",
		"@babel/plugin-transform-react-jsx"
	]
}
```

when I run gulp, I got this
![dist](https://user-images.githubusercontent.com/20679471/48199972-ad7d3c00-e398-11e8-84d6-97d3c6509117.png)
![src](https://user-images.githubusercontent.com/20679471/48199986-b4a44a00-e398-11e8-99d5-b6a9e0adf172.png)

The jsx-type-file did not be compiled,  I want to know what should I modify my code can get corret result. I would be very happy if someone can help me.

Thanks.

**Comment by loganfsmyth** [comment]
I don't see anything obviously wrong with your code. Would you be able to make a small repository that recreates the issue?

**Comment by lanyuechen** [comment]
Oh, I have figure out what the problem it is. The *.jsx file use static property in the class, so the .babelrc file should config the plugins of @babel/plugin-proposal-decorators, just like the below:

```javascript
{
	"presets": ["@babel/preset-env", "@babel/preset-react"],
	"plugins": [
		"@babel/plugin-syntax-export-default-from",
		"@babel/plugin-proposal-export-default-from",
		["@babel/plugin-proposal-decorators", {"legacy": true}],
		"@babel/plugin-proposal-class-properties"
	]
}
```

**Comment by zengkan0703** [comment]
@lanyuechen you are right, thank you, this is exactly what I need.
@loganfsmyth Thank you anyway, I have resolved this problem by @lanyuechen .
But I am a litte bit confused why babel dose not throw any error or warning when I use unsupported property in my code.

**Comment by zengkan0703** [comment]
@loganfsmyth  Thank you anyway, I will close this issue soon, have a nice day.
