### ISSUE TITLE
slow with react

### ISSUE THREAD

**Issue by Mech7** [babel/gulp-babel#17]
If i add a watch with react it takes around 29 sec to build.

**Comment by sebmck** [comment]
I need more information. Can you provide your gulpfile?

**Comment by Mech7** [comment]
Sure this is what my gulpfile looks like: https://gist.github.com/Mech7/2fb3be27652dde7f5b39
when i comment out line 30: .pipe(to5()) it goes fast again.
Am not really sure if this is a issue with gulp-babel or babel though.

**Comment by sebmck** [comment]
How big is `/home/chris/www/react-mediabank/react-mediabank/bundle.js`?

**Comment by Mech7** [comment]
it is 361 kb pretty much all of it is react

**Comment by sebmck** [comment]
@Mech7 Why are you running babel over your builds (which will also transpile unnecessary files such as react) instead of individual files?

**Comment by john-cheesman** [comment]
I'm getting the same message with Angular. I'm using Babelify and Browserify Shim as transforms and running in a Gulp task so everything is going through Babel.

**Comment by sebmck** [comment]
@john-cheesman Ignore that folder/file. You should **not** under any circumstance be transpiling vendor files through Babel as it's unnecessary overhead and there are differences between ES5 and ES6 such as implicit strict mode that will outright break vendor code.

**Comment by john-cheesman** [comment]
Sorted, thanks. I was using it as a global transform, bad idea :smile:

**Comment by Mech7** [comment]
Ah ok i didn't know i wasn't supposed to do that either :)

**Comment by bf** [comment]
Can you guys tell me how exactly you omitted babel-compilation of things like `require('react')`? Is it done by blacklisting in babel options?

**Comment by john-cheesman** [comment]
@bf There's an example in the [docs](https://babeljs.io/docs/usage/babelrc/)
