### ISSUE TITLE
Unexpected token error when trying to use spread operator

### ISSUE THREAD

**Issue by crhistianramirez** [babel/gulp-babel#172]
I have the following installed:
```json
"@babel/core": "7.2.0",
"@babel/preset-env": "7.2.0",
"@babel/plugin-proposal-object-rest-spread": "7.2.0",
"@babel/plugin-transform-destructuring": "7.2.0",
"@babel/plugin-transform-spread": "7.2.0",
```
And my config:
```javascript
.pipe( babel( {
    'presets': [
        [ '@babel/env' ]
    ],
    'plugins': [
        '@babel/plugin-proposal-object-rest-spread', 
        '@babel/plugin-transform-destructuring',
        '@babel/plugin-transform-spread'
    ]
} ) )
```

But I'm getting an error on this line:

```javascript
vm.facetQueryParams = {...vm.facetQueryParams, ...facetQueryParams};
```

What am I doing wrong?

**Comment by loganfsmyth** [comment]
Would one of you be able to make a reproducible example?

**Comment by crhistianramirez** [comment]
I can take a crack at it this evening

**Comment by crhistianramirez** [comment]
Closing due to user error. I had a step after getting source scripts but before applying babel transformations that was relying on es5 code.

**Comment by crhistianramirez** [comment]
@saiftase here is the  minimally set up repo i used to try and recreate the bug. Might help you find the root cause to your issue:

https://github.com/crhistianramirez/gulp-babel-bug-172
