### ISSUE TITLE
How do you target browsers?

### ISSUE THREAD

**Issue by hkirsman** [babel/gulp-babel#173]
I really can't figure it out. This is my example. Could somebody help?

    gulp.task('babel', function() {
      config['paths']['js'].forEach(function(path) {
        return gulp.src(path.src)
          .pipe(babel({
            presets: [
              [
                "@babel/env",
                {
                  "targets": {
                    // The % refers to the global coverage of users from browserslist
                    "browsers": [ "last 0 browsers"]
                  }
                }
              ]
            ]
          }))
          .pipe(gulp.dest(path.dest))
      });
    });

**Comment by crhistianramirez** [comment]
I'm interested in this as well. I think you might need to add a .babelrc file. The schema for the options to babel seem to indicate that presets only takes in a string array, which of course wouldn't allow for the additional options you're specifying here. Can anyone else chime in?

**Comment by ArnoMandersTfe** [comment]
I'm also interested in an example

I now have this what seems to be working but don't know a way to test this.

```
.pipe($.babel({
                    presets: [
                        [
                            '@babel/env',
                            {
                                targets: [
                                   'last 2 versions',
				   'not dead',
				   'not < 2%',
                                ],
                            }
                        ]
                    ]
                }))
```

**Comment by hkirsman** [comment]
You could try some new functions like fetch(). Seems even IE11 does not support it: https://caniuse.com/#feat=fetch The target source code should include some extra js there.

**Comment by iplus26** [comment]
I suggest you use `.browserslistrc` ([browserlist](https://github.com/browserslist)), which is widely supported by many open-source tools, Babel, Postcss, etc.

**Comment by Zardoz89** [comment]
> I suggest you use .browserslistrc (browserlist), which is widely supported by many open-source tools, Babel, Postcss, etc.

.browserslistrc isn't an option when you need to generate bundles for different browsers. Aka one for IE11 and other for FF/Chrome/Edge/Safari/Opera.

Yes, it's 2020 and some people must keep compiling webs that works on IE11.

**Comment by nicolo-ribaudo** [comment]
https://github.com/babel/gulp-babel/issues/173#issuecomment-448953020

This example is correct. As an alternative, you can use a `babel.config.js` file.
