### ISSUE TITLE
Cannot find module 'babel-preset-babel-loader'

### ISSUE THREAD

**Issue by surajSDM** [babel/gulp-babel#174]
ACT_Nurse suraj.sanwal$ **./node_modules/.bin/webpack-dev-server -d --config ./web/webpack.config.js --inline --hot --colors**

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
✖ ｢wdm｣: Hash: 239ce3096acac3256b92
Version: webpack 4.27.1
Time: 3596ms
Built at: 12/07/2018 6:34:07 PM
        Asset     Size  Chunks             Chunk Names
bundle.web.js  882 KiB    main  [emitted]  main
Entrypoint main = bundle.web.js

[0] multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./index.js 52 bytes {main} [built]

_**[./index.js] 1.47 KiB {main} [built] [failed] [1 error]**_

[./node_modules/ansi-html/index.js] 4.16 KiB {main} [built]
[./node_modules/ansi-regex/index.js] 135 bytes {main} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {main} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {main} [built]
[./node_modules/url/url.js] 22.8 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 7.78 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.61 KiB {main} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {main} [built]
[./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.27 KiB {main} [built]
[./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.11 KiB {main} [built]
    + 13 hidden modules

**ERROR in ./index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-preset-babel-loader' from '/Users/suraj.sanwal/Desktop/project/ACT_Nurse'**
- If you want to resolve "babel-loader", use "module:babel-loader"
    at Function.module.exports [as sync] (/Users/suraj.sanwal/Desktop/project/ACT_Nurse/node_modules/resolve/lib/sync.js:43:15)
    at resolveStandardizedName (/Users/suraj.sanwal/Desktop/project/ACT_Nurse/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePreset (/Users/suraj.sanwal/Desktop/project/ACT_Nurse/node_modules/@babel/core/lib/config/files/plugins.js:58:10)
    at loadPreset (/Users/suraj.sanwal/Desktop/project/ACT_Nurse/node_modules/@babel/core/lib/config/files/plugins.js:77:20)
    at createDescriptor (/Users/suraj.sanwal/Desktop/project/ACT_Nurse/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/Users/suraj.sanwal/Desktop/project/ACT_Nurse/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/suraj.sanwal/Desktop/project/ACT_Nurse/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/suraj.sanwal/Desktop/project/ACT_Nurse/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Users/suraj.sanwal/Desktop/project/ACT_Nurse/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./index.js main[2]
ℹ ｢wdm｣: Failed to compile.

**here is my webpack.config**

// web/webpack.config.js

const path = require("path");
// const webpack = require("webpack");

const appDirectory = path.resolve(__dirname, "../");

// This is needed for webpack to compile JavaScript.
// Many OSS React Native packages are not compiled to ES5 before being
// published. If you depend on uncompiled packages they may cause webpack build
// errors. To fix this webpack can be configured to compile to the necessary
// `node_module`.
const babelLoaderConfiguration = {
  test: /\.js$/,
  // Add every directory that needs to be compiled by Babel during the build.
  include: [
    path.resolve(appDirectory, "index.js"),
    path.resolve(appDirectory, "src"),
    path.resolve(appDirectory, "node_modules/react-native-uncompiled")
  ],
  exclude: /node_modules/,
  use: {
    loader: "babel-loader",
    options: {
      cacheDirectory: true,
      // The 'react-native' preset is recommended to match React Native's packager
      presets: ["react-native"],
      // Re-write paths to import only the modules needed by the app
      plugins: ["react-native-web"]
    }
  }
};

// This is needed for webpack to import static images in JavaScript files.
const imageLoaderConfiguration = {
  test: /\.(gif|jpe?g|png|svg)$/,
  use: {
    loader: "url-loader",
    options: {
      name: "[name].[ext]"
    }
  }
};

module.exports = {
  entry: [
    // load any web API polyfills
    // path.resolve(appDirectory, 'polyfills-web.js'),
    // your web-specific entry file
    path.resolve(appDirectory, "index.js")
  ],

  // configures where the build ends up
  output: {
    filename: "bundle.web.js",
    path: path.resolve(appDirectory, "dist")
  },

  // ...the rest of your config

  module: {
    rules: [babelLoaderConfiguration, imageLoaderConfiguration]
  },

  resolve: {
    // This will only alias the exact import "react-native"
    alias: {
      "react-native$": "react-native-web"
    },
    // If you're working on a multi-platform React Native app, web-specific
    // module implementations should be written in files using the extension
    // `.web.js`.
    extensions: [".web.js", ".js"]
  }
};

and this is babelrc
{
  "presets": [
    [
      "babel-loader",
      {
        "targets": {
          "browsers": ["last 2 versions"],
          "node": "current"
        }
      }
    ],
    ["react"]
  ]
}

**and this is my development dependency**

 "devDependencies": {
    "babel-jest": "23.6.0",
    "babel-loader": "^8.0.4",
    "babel-plugin-react-native-web": "^0.9.9",
    "babel-preset-react-native": "^5",
    "eslint": "^5.5.0",
    "eslint-plugin-react": "^7.11.1",
    "husky": "^0.14.3",
    "jest": "23.6.0",
    "lint-staged": "^7.2.2",
    "metro-react-native-babel-preset": "0.50.0",
    "prettier": "1.14.2",
    "react-test-renderer": "16.6.1",
    "url-loader": "^1.1.2",
    "webpack": "^4.27.1",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.10"
  },

Please suggest me something regarding solution

**Comment by loganfsmyth** [comment]
```
{
"presets": [
[
"babel-loader",
```
does not make sense. `babel-loader` is not a preset.

**Comment by surajSDM** [comment]
> ```
> {
> "presets": [
> [
> "babel-loader",
> ```
> does not make sense. `babel-loader` is not a preset.

updated code with a valid preset used 

**{
  "presets": ["env"]
}
**

now issue is going like this ===>

ERROR in ./App.js 20:6
Module parse failed: Unexpected token (20:6)
**You may need an appropriate loader to handle this file type.**
|   render() {
|     return (
**>       <View style={styles.container}>**
|         <Text style={styles.welcome}>Welcome to React Native!</Text>
|         <Text style={styles.instructions}>To get started, edit App.js</Text>
 @ ./index.js 4:0-24 7:45-48
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./index.js


after using valid preset as well not able to run code, can you please update what i am doing wrong here???

**Comment by surajSDM** [comment]
i got the solution, i have done few changes in web config file, due to this it was not able to compile. 
now another issue i am getting, i have used preset es2015 and it's looking not supporting ES6 standards, is there any way to use . es6 module to react native web???
