### ISSUE TITLE
react support 

### ISSUE THREAD

**Issue by Mech7** [babel/gulp-babel#18]
I am trying the react support in babel with browserify & watchify only i am getting an error:

Gulpfile
https://gist.github.com/Mech7/39998f130bc0917fad39

```
[21:30:53] Browserify Error 
./src/mediabank.js:1
var profile = <div>
              ^
```

On some very simple test code (taken from the page):

```
var profile = <div>
  <img src="avatar.png" class="profile" />
  <h3>{[user.firstName, user.lastName].join(' ')}</h3>
</div>;
```

**Comment by sebmck** [comment]
This error is being thrown by one of the previous gulp plugins. Please use the [gitter room](https://gitter.im/babel/babel) for support and questions, thanks!
