### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by 9yues** [babel/gulp-babel#181]
我使用gulp-babel 编译 async await 网页上会报错
node: 8.9.1
npm: 5.5.1
cnpm: 6.0.0
![image](https://user-images.githubusercontent.com/19297519/54006300-b7bd1480-4197-11e9-92e2-bf74008801c3.png)

附代码：
![image](https://user-images.githubusercontent.com/19297519/54006303-bbe93200-4197-11e9-8723-1e7675dd3001.png)
![image](https://user-images.githubusercontent.com/19297519/54006304-bc81c880-4197-11e9-8419-904f519160cd.png)

![image](https://user-images.githubusercontent.com/19297519/54006315-c7d4f400-4197-11e9-8f8f-126367dd45fa.png)

**Comment by vans163** [comment]
Same problem, this is so annoying

**Comment by loganfsmyth** [comment]
This does not work because Babel does not handle module bundling. Generally you'd use `gulp-babel` to compile files that would be loaded in Node, which has its own module loader. To bundle code like this for a browser you'd want to use Webpack.
