### ISSUE TITLE
The packaging process was terminated when i use "babel"

### ISSUE THREAD

**Issue by Super-Mumoo** [babel/gulp-babel#184]
not use：
![image](https://user-images.githubusercontent.com/38457677/58934648-ac30b800-879d-11e9-8b1f-fe1ad36b05c5.png)
output：
![image](https://user-images.githubusercontent.com/38457677/58934680-c4a0d280-879d-11e9-97f7-13aab653afc2.png)
all finished.

use:
![image](https://user-images.githubusercontent.com/38457677/58934785-13e70300-879e-11e9-8ff1-978c9c84e20b.png)
output:
![image](https://user-images.githubusercontent.com/38457677/58934789-19dce400-879e-11e9-893d-3a987e75ea24.png)
Interruption after starting 'flie'

**Comment by loganfsmyth** [comment]
Generally this means that you have a syntax error in one of your files. You'd have to add `.on('error', e => console.error(e))` to log it somewhere.

**Comment by dkornilove** [comment]
@Super-Mumoo did you find a error? experiencing the same issue here

**Comment by Super-Mumoo** [comment]
> @Super-Mumoo did you find a error? experiencing the same issue here

I almost forgot the issues I submitted, because I left my job shortly after I submitted the issues, so I didn't pay any more attention this issues. 

The later colleagues in charge of the project seem to have changed their strategy. I'll ask and I'll get back to you if I get a helpful answer to this question

**Comment by FrontEndNoah** [comment]
> @Super-Mumoo did you find a error? experiencing the same issue here

I almost forgot the issues I submitted, because I left my job shortly after I submitted the issues, so I didn't pay any more attention this issues.

I asked my former colleague. He tell me there is problem of code instead babel, he print the error message in the error callback and fixed.

like this
![image](https://user-images.githubusercontent.com/38457677/143862933-b24a1464-9e71-4589-b0ab-fa71a8265e0c.png)

**Comment by FrontEndNoah** [comment]
> Generally this means that you have a syntax error in one of your files. You'd have to add `.on('error', e => console.error(e))` to log it somewhere.

Sorry to reply you now, cause  I left my job shortly after I submitted the issues, so I didn't pay any more attention this issues. it's really a problem of code. I have closed this issue.
