### ISSUE TITLE
Globbing patterns in white/blacklist?

### ISSUE THREAD

**Issue by brianfeister** [babel/gulp-babel#19]
I was surprised that gulp-babel doesn't like this globbing pattern `'client/{app,common}/**/*.js` ... any reason for this?  Would a PR be welcome?  I would just be adding [`glob`](https://www.npmjs.com/package/glob) and then running it on `white/blacklist` parameters.

**Comment by sindresorhus** [comment]
If you need globbing on the whitelist/blacklist it needs to be added to Babel, and not this plugin.
