### ISSUE TITLE
Using generators/async-await etc. without modular bundler

### ISSUE THREAD

**Issue by kokoshneta** [babel/gulp-babel#197]
I’m not sure if this is the best place to ask, but here goes…

The documentation for this package says that,

> If you're attempting to use features such as generators, you'll need to add `transform-runtime` as a plugin, to include the Babel runtime. Otherwise, you'll receive the error: `regeneratorRuntime` is not defined.

Unfortunately, as noted in [several previous issues](https://github.com/babel/gulp-babel/issues?utf8=%E2%9C%93&q=%22require+is+not+defined%22) this just yields the error “`require` is not defined” because:

> This does not work because Babel does not handle module bundling. Generally you'd use `gulp-babel` to compile files that would be loaded in Node, which has its own module loader. To bundle code like this for a browser you'd want to use Webpack.
— [loganfsmyth](https://github.com/babel/gulp-babel/issues/181#issuecomment-490338880)

But Webpack, Browserify, Node module bundlers, etc. are not for everyone. Personally, I have no interest in having to set up complex module bundlers for every new project – especially not when they’re completely unnecessary, except for this one tiny aspect.

Is there some way to use `gulp-babel` to transpile ES6 to ES5 with these features, but **without** using a module bundler, yielding transpiled JS files that can be used as-is in a browser?

**Comment by nicolo-ribaudo** [comment]
You can add `<script src="https://unpkg.com/browse/regenerator-runtime@0.13.4/runtime.js"></script>` to your HTML file, _before_ loading your JavaScript code.

**Comment by irbian** [comment]
thanks, I´ll try!

**Comment by icassidyif** [comment]
<script src="https://unpkg.com/browse/regenerator-runtime@0.13.4/runtime.js"></script> 
don't work. Do you  have another link?

**Comment by nicolo-ribaudo** [comment]
https://unpkg.com/regenerator-runtime@0.13.4/runtime.js

**Comment by aprinciple** [comment]
`plugins: [
  ['@babel/transform-runtime']
]`

**Comment by lb1129** [comment]
![image](https://github.com/babel/gulp-babel/assets/24662243/c8120885-6c8d-4b4c-a2eb-36be47149cfe)
config like this

**Comment by lb1129** [comment]
or
![image](https://github.com/babel/gulp-babel/assets/24662243/6cdb34c7-10c9-413d-84f3-59da376d5433)

**Comment by nicolo-ribaudo** [comment]
With new versions of Babel it's not necessary anymore to use `transform-runtime` or manually include `regeneratorRuntime` :)
