### ISSUE TITLE
Plugins is not just an array of strings

### ISSUE THREAD

**Issue by danielo515** [babel/gulp-babel#201]
Hello, this is the current definition of what plugins config option looks like:

```
    plugins?: string[],
```

Which is not correct because plugins can be an array of strings, or an array of arrays containing both strings and config for each module. Please take a look at:
https://babeljs.io/docs/en/plugins#plugin-options

Regards

**Comment by nicolo-ribaudo** [comment]
This should be reported to https://github.com/DefinitelyTyped/DefinitelyTyped, the TS types are not maintained in this repository.
