### ISSUE TITLE
Can I know that is the default `gupl-babel` including polyfill by default

### ISSUE THREAD

**Issue by yang-wei** [babel/gulp-babel#25]
The docs said 
 > To include the polyfill you need to require it at the top of the entry point to your application.
```js
require("babel/polyfill");
```

[gulp-babel](https://github.com/babel/gulp-babel/blob/master/index.js#L7) is doing
```
require("babel-core")
```
So I think polyfill is not included but again the [doc](http://babeljs.io/docs/usage/polyfill/#usage-in-browser) said that polyfill is 
 > Available from the browser-polyfill.js file within a babel-core npm release

Can you help me to clear this up?

**Comment by sebmck** [comment]
It's not included by default, no.

**Comment by mmahalwy** [comment]
@yang-wei how'd you add it?

**Comment by yang-wei** [comment]
I was hoping to exclude it.
If you want to add it, I think 
```
require('babel/register')
```
will do the tricks. http://babeljs.io/docs/usage/require/#usage

@mmahalwy

**Comment by mmahalwy** [comment]
@yang-wei but I need it to run in frontend js world.

**Comment by yang-wei** [comment]
@mmahalwy 
Then include `browser-polyfill.js`
http://babeljs.io/docs/usage/polyfill/#usage-in-browser
