### ISSUE TITLE
How to use the polyfill

### ISSUE THREAD

**Issue by agzam** [babel/gulp-babel#27]
What's the best way to use the polyfill? I couldn't find the better way but to include it into glob like this:

```
gulp.task('default', function () {
    var polyfill = './node_modules/gulp-babel/node_modules/babel-core/browser-polyfill.js'

    return gulp.src(['src/**/*.js', polyfill])
    .pipe(sourcemaps.init())
    .pipe(babel())
    .pipe(concat('all.js'))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('dist'));
});
```

Is there any better way?

**Comment by MikeMcElroy** [comment]
This looks like it will re-compile the browser-polyfill through babel, which is probably not what you want?  I'd suggest using mergeStream and then concat --
```js
return mergeStream(
  gulp.src(polyfill),
  gulp.src('src/**/*.js')
    .pipe(sourcemaps.init())
    .pipe(babel())
    .pipe(sourcemaps.write('.'))
  )
  .pipe(concat('all.js'))
  .pipe(gulp.dest('dist'));
```

**Comment by sbalay** [comment]
Any other suggestions on this one?

**Comment by joaomilho** [comment]
I would really like to be able to use the polyfill without needing a compile step, specially for demo purposes. Adding it to a CDN would also be lovely.

**Comment by alexbeletsky** [comment]
Really interesting in that as well.

**Comment by metaraine** [comment]
In Pull Request #38 I suggested adding a section to the README which clarifies how to include the babel runtime. I'm not sure if that is the same as the browser polyfill though.

**Comment by WangJi** [comment]
You may try this:

npm install `babel-runtime`

```javascript
gulp.pipe(babel({
            optional: ['runtime']
        }));
```

This works for me in Node environment.

**Comment by zloirock** [comment]
@WangJi `runtime` does not add **all** polyfill features.

**Comment by sindresorhus** [comment]
https://babeljs.io/docs/usage/polyfill/#usage-in-browser

**Comment by laggingreflex** [comment]
How would one do this in babel 6? It gives the error `Unknown option: base.optional`

**Comment by jy95** [comment]
@MikeMcElroy I tested your solution and it just doesn't work (the generated file is full of error). The solution provided by @agzam works great

**Comment by hzoo** [comment]
You just need to load the polyfill before the other files in an entry point. I would recommend https://webpack.js.org/ instead of simply concating files which can have some potential issues.
