### ISSUE TITLE
Update documentation for inline sourcemaps, or optional config for babel

### ISSUE THREAD

**Issue by michaelBenin** [babel/gulp-babel#29]
For my needs, I was able to accomplish inline source maps passing options directly to babel. 

The use case is transpiling server side node.

```
gulp.task('babel', function () {
  return gulp.src('server/**/*.js')
    .pipe(babel({
      sourceMaps: 'inline'
    }))
    .pipe(gulp.dest(DEST));
});
```

**Comment by sindresorhus** [comment]
The blessed source map way is this: https://github.com/babel/gulp-babel#source-maps

You can do inline source map with it too.
