### ISSUE TITLE
Add babel-runtime option

### ISSUE THREAD

**Issue by omerts** [babel/gulp-babel#34]
In order to avoid having to use babel/polyfill in a library, which is not recommended, please add babel-runtime to the project, and that way we can use the babels option:
```
 { optional: ["runtime"] }
```

**Comment by sebmck** [comment]
You can already set any option that Babel supports. You can see the documentation in the [README](https://github.com/babel/gulp-babel#babeloptions). Thanks!

**Comment by omerts** [comment]
@sebmck The babel docs say: 
```
The package babel-runtime is required for this transformer
```

**Comment by sebmck** [comment]
Yep. Just install it via `npm install babel-runtime`.

**Comment by omerts** [comment]
@sebmck Ok thought it might be a good idea to add it as a dependency here, but on second thought you are right. Thank you.
