### ISSUE TITLE
Using generator in the code gives error.

### ISSUE THREAD

**Issue by lokeshjainRL** [babel/gulp-babel#36]
I currently started using `gulp-babel` in our project. so far so good, nice work.

In the gulp task

```
all.javascripts().pipe(babel()).pipe(gulp.dest(paths.dist));
```

When i used generator

```javaScript

var gen = function*(start, end, step){
// code...
}

```
 in my code the compiled code give me  this error

```
regeneratorRuntime is not defined.
```

How to use babel fullest. this code works on babel editor. I see they include some polyfill.
How to tell `gulp-babel` to include one.
Can't this be made automatic. if Code requires some polyfill, it will do it automatically?

**Comment by sebmck** [comment]
You can read more about the polyfill in the docs [here](https://babeljs.io/docs/usage/polyfill/). There's nothing special about it's usage with `grunt-babel` and there shouldn't really be anything specific anyway.

> Can't this be made automatic. if Code requires some polyfill, it will do it automatically?

The heuristics for determining if a polyfill is required is extremely muddled. It's up to the user to specify it and it should not be an opinion imposed by default.

If you have any further questions or support queries feel free to checkout some of the resources included in the [Babel README](https://github.com/babel/babel#readme):

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

Thanks! :blush:

**Comment by lokeshjainRL** [comment]
Thanks for the info.
This can be great value for the end user if the required polyfill will be
available by default.
naive user like me come to know about this by surprise, when they see error.



On Thu, Aug 13, 2015 at 6:07 PM, Sebastian McKenzie <
notifications@github.com> wrote:

> You can read more about the polyfill in the docs here
> <https://babeljs.io/docs/usage/polyfill/>. There's nothing special about
> it's usage with grunt-babel and there shouldn't really be anything
> specific anyway.
>
> Can't this be made automatic. if Code requires some polyfill, it will do
> it automatically?
>
> The heuristics for determining if a polyfill is required is extremely
> muddled. It's up to the user to specify it and it should not be an opinion
> imposed by default.
>
> If you have any further questions or support queries feel free to checkout
> some of the resources included in the Babel README
> <https://github.com/babel/babel#readme>:
>
> For questions and support please visit the Slack community
> <https://babel-slack.herokuapp.com> or StackOverflow
> <http://stackoverflow.com/questions/tagged/babeljs>.
>
> Thanks! [image: :blush:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/gulp-babel/issues/36#issuecomment-130654023>.
>



-- 
Lokesh kumar Jain
*ReachLocal Services Pvt. Ltd.*
5-B | Express Zone Towers  |  Patel Vanika |  Western Express Highway |
Goregaon (E) | Mumbai – 400097
www.reachlocal.com | www.reachservices.co.in
