### ISSUE TITLE
Error The code generator has deoptimised

### ISSUE THREAD

**Issue by senja006** [babel/gulp-babel#39]
[BABEL] Note: The code generator has deoptimised the styling of "/Users/.../markup/static/js/libraries/jquery.js" as it exceeds the max of "100KB".

**Comment by sebmck** [comment]
Posting a logline isn't really helpful. That error is not produced by `gulp-babel` but from `babel-core`. The message is pretty self explanatory. You shouldn't be passing third party vendor assets through Babel.
