### ISSUE TITLE
Add an option to create symlink for all non-JavaScript files

### ISSUE THREAD

**Issue by gajus** [babel/gulp-babel#40]
The original issue: http://stackoverflow.com/questions/32634521/is-there-a-variable-that-refers-to-the-package-base-directory?noredirect=1#comment53117653_32634521

Using gulp-babel to transpile code directories leaves out dependencies that are not JavaScript (e.g. JSON). All relative references to these dependencies will fail. Two possible solutions:

* Create a symlink
* Append a string to every require that resolves path to `./src/`

**Comment by benderTheCrime** [comment]
There is actually and option to "copy files" from the Babel CLI:
```bash
babel src --out-dir dist --copy-files
```
Whether symbolic or not, I am looking for gulp-babel to support this option as well. I have tried both `copyFiles: true` and `'copy-files': true` in the options hash piped to Babel. Is this in the plan for a future version of this package?

**Comment by sebmck** [comment]
That open is only available via the CLI.

**Comment by benderTheCrime** [comment]
Is it perhaps possible to edit this package to use the CLI as opposed to the `babel.transform` function? I understand why transform does not have the capacity to copy files from anywhere to anywhere, but this seems like something that is a valid (and perhaps widely needed) use case with respect to transpiling a directory with gulp

**Comment by benderTheCrime** [comment]
I have a temporary workaround with gulp-copy, but I am not proud of the code:

```javascript
gulp.task('babel', function(cb) {
    gulp.src(SRC).pipe(babel({
        comments: false
    })).pipe(gulp.dest(TRANSPILED_SRC)).on('finish', function() {
        gulp.src(`${SRC_DIR}/templates/**`).pipe(
            copy(`${TRANSPILED_SRC}/templates`, {
                prefix: 2
            })
        );
        cb();
    });
});
```

**Comment by gajus** [comment]
You do not need [`gulp-copy`](https://www.npmjs.com/package/gulp-copy) for copying files.

```js
gulp.task('copy', () => {
    return gulp
        .src('./src/**/*')
        .pipe(gulp.dest('./dist'));
});

gulp.task('build-es5', ['copy'], () => {
    return gulp
        .src('./src/**/*.js')
        .pipe(sourcemaps.init())
        .pipe(babel())
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest('./dist'));
});
```

**Comment by benderTheCrime** [comment]
How the copy is accomplished without the `copy-files` options seems irrelevant to not having the `copy-option`. I just posted my code to show that it was inconvenient to not have the option in the gulp plugin. I feel as though issue resolution should imply a response to the original issue and not a workaround even if the resolution is "We don't want to do this," but hey, it's not my tool, I'm just a lowly user.

**Comment by sebmck** [comment]
@benderTheCrime The person who closed this is the person who opened the issue :)

**Comment by gajus** [comment]
> How the copy is accomplished without the copy-files options seems irrelevant to not having the copy-option. I just posted my code to show that it was inconvenient to not have the option in the gulp plugin. I feel as though issue resolution should imply a response to the original issue and not a workaround even if the resolution is "We don't want to do this," but hey, it's not my tool, I'm just a lowly user.

`gulp-babel` as a `gulp` plugin has a single responsibility – compile JavaScript files down to ES5. It is not up to `gulp-babel` to do anything beyond that.

This is not even a workaround – `gulp` is designed to work with files.

On the other hand, `babel` as a CLI program cannot leverage the flexibility of `gulp` and it is good that it integrates a cross-platform friendly feature to copy over all files at the time of compiling JavaScript files.

**Comment by sindresorhus** [comment]
@benderTheCrime That's not how it's done with Gulp. Idionmatic Gulp prefers separate plugins doing one thing, instead of every plugins doing everything. You already got a good answer. Another option is to source all the files, and use `gulp-if` to only run Babel on the JS files. `gulp-filter` would work too if you have many plugins that should run on only JS files.

**Comment by benderTheCrime** [comment]
@sindresorhus that makes sense and now that you put it that way (in the context of gulp), I understand. Thanks!
