### ISSUE TITLE
How to keep the `.jsx` extensions ?

### ISSUE THREAD

**Issue by egoist** [babel/gulp-babel#45]
I use babel to compile `.jsx` to `.js` files but I want the compiled files to keep the `.jsx` extension.

Well My gulp task is:

```javascript
gulp.src(['./src/**/*.jsx'])
    .pipe(babel())
    .pipe(gulp.dest('./app'))
```

Any idea how to config this?

**Comment by sindresorhus** [comment]
Already been answered in another issue.

**Comment by egoist** [comment]
thanks, due to https://github.com/babel/gulp-babel/issues/24 I think there's no need to keep that `.jsx` extension.

**Comment by RIAEvangelist** [comment]
@sindresorhus  Would be awesome to reference the other issue so people would know where to look.
