### ISSUE TITLE
Cannot find module 'babel-runtime/regenerator'

### ISSUE THREAD

**Issue by owcc** [babel/gulp-babel#50]
I use react 0.14/babel 6.0.14/koa, this is my **.babelrc** file:
{
    presets: ['stage-0', 'es2015', 'react'],
    plugins: ['transform-runtime']
}

**Comment by marsoln** [comment]
I got the same error.

> module.js:339
    throw err;
    ^

> Error: Cannot find module 'babel-runtime/core-js/get-iterator'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\Marsoln Licher\Lib\exampleProj\dist\app.js:3:21)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)

----
and here is my source file:

    var fibonacci = {
      [Symbol.iterator]: function*() {
        "use strict";
        let pre = 0, cur = 1;
        while (true) {
          pre = (cur += pre) - pre;
          yield cur;
        }
      }
    };
    
    if (require.main === module) {
      var n = Number(process.argv[2]);
      for (let r of fibonacci) {
        if (r > 1000)
          break;
        console.log(`${r}`);
      }
    }
----
then compiled file:

    "use strict";
    
    var _getIterator2 = require("babel-runtime/core-js/get-iterator");
    
    var _getIterator3 = _interopRequireDefault(_getIterator2);
    
    var _defineProperty2 = require("babel-runtime/helpers/defineProperty");
    
    var _defineProperty3 = _interopRequireDefault(_defineProperty2);
    
    var _regenerator = require("babel-runtime/regenerator");
    
    var _regenerator2 = _interopRequireDefault(_regenerator);
    
    var _iterator2 = require("babel-runtime/core-js/symbol/iterator");
    
    var _iterator3 = _interopRequireDefault(_iterator2);
    
    function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
    
    var fibonacci = (0, _defineProperty3.default)({}, _iterator3.default, _regenerator2.default.mark(function _callee() {
      var pre, cur;
      return _regenerator2.default.wrap(function _callee$(_context) {
        while (1) {
          switch (_context.prev = _context.next) {
            case 0:
              pre = 0, cur = 1;
    
            case 1:
              if (!true) {
                _context.next = 7;
                break;
              }
    
              pre = (cur += pre) - pre;
              _context.next = 5;
              return cur;
    
            case 5:
              _context.next = 1;
              break;
    
            case 7:
            case "end":
              return _context.stop();
          }
        }
      }, _callee, this);
    }));
    
    if (require.main === module) {
      var n = Number(process.argv[2]);
      var _iteratorNormalCompletion = true;
      var _didIteratorError = false;
      var _iteratorError = undefined;
    
      try {
        for (var _iterator = (0, _getIterator3.default)(fibonacci), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
          var r = _step.value;
    
          if (r > 1000) break;
          console.log("" + r);
        }
      } catch (err) {
        _didIteratorError = true;
        _iteratorError = err;
      } finally {
        try {
          if (!_iteratorNormalCompletion && _iterator.return) {
            _iterator.return();
          }
        } finally {
          if (_didIteratorError) {
            throw _iteratorError;
          }
        }
      }
    }

----
It looks like something goes wrong with the compiled module paths.

**Comment by ustims** [comment]
I've tried to install "babel-runtime" separately and it seems that only old 5.3.0 version works.

So for now it could be solved by:
```bash
npm install babel-runtime@5.3.0
```

**Comment by achal7** [comment]
worked for me. 
i also have tried to install babel-core and babel-preset-es2015 one version earlier and that worked as well. but i think this one is better option, so just stick with latest version and replace only the runtime version to earlier.

**Comment by erikvold** [comment]
I have the same issue:

I was using node version 5.11.0 and npm version 3.8.6 installed via homebrew for osx 10.11.4  which was working fine! then committed my changes, and noticed this error in circle-ci:

    Error: Cannot find module 'babel-runtime/regenerator'

circle-ci was using nvm 4.0 so I tried the same with nvm and got the same error, then I tried nvm use 5.11.0 and nvm use stable, and got the same error every-time.

**Comment by loganfsmyth** [comment]
If you are using `transform-runtime`, you need to have `babel-runtime@6` in your `dependencies`.

**Comment by erikvold** [comment]
> If you are using transform-runtime, you need to have babel-runtime@6 in your dependencies

babel-runtime is a dependency of babel-plugin-transform-runtime so I'm not sure why I would need to add it again..

Also not sure why that would not be mentioned at https://www.npmjs.com/package/babel-plugin-transform-runtime ..

**Comment by erikvold** [comment]
>  I tried nvm use 5.11.0 and nvm use stable, and got the same error every try.

hmm weird I tried with nvm 5.11.0 again and that worked, I might've forgotten to wipe the `node_modules` folder after trying `nvm 4.0` last time.  Everytime I wipe the node_modules folder and nvm use 4.0 I get the error above however.

**Comment by ORESoftware** [comment]
putting transform-runtime as a plugin in my .babelrc worked for me

```
{
  "presets": [
    "es2015",
    "stage-3"
  ],
  "plugins": ["transform-runtime"]
}
```

**Comment by amok** [comment]
I've deleted node_modules, did `npm i` and then got following error

```
Cannot find module 'babel-runtime/core-js/json/stringify'
```

It's fixed by `rm -rf node_modules; npm i` again
Looks like it's npm issue..

```
{ npm: '3.9.5',
  node: '4.4.5' }
```

**Comment by albertbuchard** [comment]
I had the same error.

In my project folder, I had to : 
`
$ npm uninstall babel-preset-es2015
$ sudo npm uninstall -g babel-cli
`

Then redownload/install latest version of node/npm, then : 
`
$ sudo npm install -g babel-cli
$ npm install babel-preset-es2015
`

My .babelrc : 
`
{"presets": ["es2015"]}
`

**Comment by yangbiaoit** [comment]
npm install babel-runtime

**Comment by Sarke** [comment]
> If you are using transform-runtime, you need to have babel-runtime@6 in your dependencies.

> npm install babel-runtime

@loganfsmyth and @yangbiaoit why is that necessary though?  If we have `babel-core` installed, which depends on `babel-runtime`, shouldn't that take care of it?

**Comment by loganfsmyth** [comment]
@Sarke Code that is compiled with `transform-runtime` enabled needs to depend on `babel-runtime` because `transform-runtime` injects references to that module. `babel-core` depends on `babel-runtime` because we compile `babel-core` with `transform-runtime`, but that is unrelated user-compiled code.

**Comment by loganfsmyth** [comment]
Because `npm@3` flattens dependencies, installing `babel-core` can have the side-effect of installing `babel-runtime` into your root `node_modules`, but your code `package.json` should still include it since you npm3's flattening is for deduplication purposes, not dependency purposes. For instance, because `babel-core` is commonly in `devDependencies`, you'll lose the `babel-runtime` side-effect installation in production builds, or if we ever release a new major version of `babel-runtime`, if your code doesn't explicitly list that it depends on `babel-runtime@6`, you'd be updated to a potentially incompatible version because you didn't have it in your dependencies properly.

**Comment by Sarke** [comment]
That makes sense, thank you.

⁣​

**Comment by hzoo** [comment]
You need `babel-runtime` as part of your dependencies since it will be used in the user built code like logan mentioned.
