### ISSUE TITLE
Source-maps source path is wrong

### ISSUE THREAD

**Issue by vzaidman** [babel/gulp-babel#54]
when babeling a simple es6 file exactly like in the example,
the "sources" property of the ".map" file is it's name instead of path.

so if you have two files with the same name they will collide in the "sources" directory when debugging.

**Comment by timjchin** [comment]
Ran into the same issue, we weren't seeing any folder information in the sourcemaps, and @vzaidman's commit above (ad5f6c5) fixed it.  :+1:

**Comment by glen-84** [comment]
@sindresorhus Could you please apply this fix? Otherwise we can't use sourcemaps. :disappointed:

**Comment by vzaidman** [comment]
its a temporary fix, i wouldn't recommend using it.
the fix should be somewhere deeper. (in the preset i think)

**Comment by glen-84** [comment]
Right, I should have said "please fix this" instead of "please apply this fix". :smile:

**Comment by clarkmalmgren** [comment]
I am seeing the same issue.  @vzaidman's fix worked for me.  Not sure why it is considered temporary.

**Comment by vzaidman** [comment]
look at the code.
replaceExt changes source map's pathes to filenames and then we change it back instead of replaceExt setting the pathes right.

**Comment by clarkmalmgren** [comment]
So the problem was not in the renaming of the file but not in explicitly setting the source.  I kept the `replaceExt(...)` line and just added a line to keep the source file name mapping correct.  Submitting a pull request.

**Comment by vzaidman** [comment]
I disagree.
The maps' source should not be changed and then changed again. They has to be set right inside the applySourceMap function.
