### ISSUE TITLE
Avoid changing file extension

### ISSUE THREAD

**Issue by louy** [babel/gulp-babel#67]
Currently `gulp-babel` changes all file extensions to `.js`. I don't want that. It should probably be optional as babel can output things like jsx & flow.

I was able to avoid this by removing the [two lines](https://github.com/babel/gulp-babel/blob/master/index.js#L35-L41) here. Can you make an option for this?

**Comment by sindresorhus** [comment]
> babel can output things like jsx & flow.

Why would you output JSX or Flow? You can't run that natively anywhere.

**Comment by louy** [comment]
I know, but my build process consists of two steps and I want jsx to be the output of the first one. Basically to keep the build process faster.

To give you a better idea about this, I use `tsx` and `ts` on a client-server shared codebase. I use webpack to generate the client-side code while using babel to generate the server-side one. I can't use gulp for the whole process because I want hot-reloading as well, and I can't use webpack for the whole process because I want to get useful error stack traces in my server. I feed jsx to webpack to make the generation of server-side code faster.

I know this can probably be done in a better way, but I don't want to waste another day trying to do it. It will probably stop working with the next version of babel/webpack/typescript and I can do it again then.

The problem with `gulp-babel` is that I don't know original file extensions because some of them are `tsx` files while others are `ts` files. This is why I need it not to touch filenames.

**Comment by sindresorhus** [comment]
I think that's pretty edge-casy. I'd suggest you use https://github.com/sindresorhus/gulp-revert-path instead of forcing every plugin to implement an option.

**Comment by louy** [comment]
I didn't even know that it's possible for a plugin to know previous paths. That's a good solution. Thanks.
