### ISSUE TITLE
Babel cut my brackets

### ISSUE THREAD

**Issue by dslpp056193** [babel/gulp-babel#82]
What i use:
``` JSON
"babel-preset-es2015": "^6.6.0",
"gulp-babel": "^6.1.2",
```
What i compile:
``` JS
var path = ( x=> x)();
var someF = (function(x){
    return x + path;
})();
```
**What i get:**
``` JS
var path = function (x) {
    return x;
}();
var someF = function (x) {
    return x + path;
}();
```
**What i need:**
``` JS
var path = (function (x) {
    return x;
})();
var someF = (function (x) {
    return x + path;
})();
```

Where is my brackets?
I searched error half at hour. And very surprised.
Maybe something i do wrong?

Init babel:
``` JS
.pipe(babel({
    presets: ['es2015']
}))
```

**P.S.:** if try this on babel website (inside "try it out") this error not observed

**Comment by sindresorhus** [comment]
https://github.com/babel/babel#looking-for-support
