### ISSUE TITLE
Gulp-Babel not works with imports

### ISSUE THREAD

**Issue by azat-io** [babel/gulp-babel#85]
Hi there!

I have a trouble about working with gulp-babel. It looks strange, `import` not works there:

Part of my **package.json**:
```json
{
  "devDependencies": {
    "babel-preset-es2015": "6.6.0",
    "babel-preset-react": "6.5.0",
    "gulp": "3.9.1",
    "gulp-babel": "6.1.2",
    "gulp-uglify": "1.5.3",
    "react": "0.14.8",
    "react-dom": "0.14.8"
  }
}
```

Js task of my **gulpfile.js:**
```js
const babel = require('gulp-babel');
const gulp = require('gulp');
const uglify = require('gulp-uglify');

gulp.task('js', function () {
  gulp.src('src/js/App.js')
  .pipe(babel())
  .pipe(uglify())
  .pipe(gulp.dest('dist/js'));
});
```

**.babelrc:**
```json
{
  "presets": ["es2015", "react"]
}
```

So. It must works with imports. For example it's my main Js file:

**src/js/App.js:**
```jsx
import React from 'react'
import ReactDOM from 'react-dom'
import Main from './Main.js'

ReactDOM.render(<Main />, document.body);
```

This file should import `react` from `node_modules/react/` and import `Main.js`.

**src/js/Main.js:**
```jsx
import React from 'react'

export default class Main extends React.Component {
  render() {
    return (
      <div>
        <h1>Hello!</h1>
      </div>
    );
  }
}
```

There is no errors. All works good, but imports are not works. What's wrong here?

**Comment by loganfsmyth** [comment]
```
import App from './Main.js'
ReactDOM.render(<Main />, document.body);
```

You import the component with the name `App` but then use `<Main />` instead of `<App />`, that see like the main issue.

**Comment by azat-io** [comment]
@loganfsmyth My bad. Update issue. :smiley:

**Comment by sindresorhus** [comment]
Please use the dedicated support channels for support questions: https://github.com/babel/babel#looking-for-support

**Comment by Bound3R** [comment]
@azat-io hi, how you solved this problem?, something similar happens to me, but without a reactjs.
