### ISSUE TITLE
下载提示安装left-pad出错

### ISSUE THREAD

**Issue by GuoYongfeng** [babel/gulp-babel#87]

**Comment by hzoo** [comment]
Thanks for reporting! left-pad shouldn't be an issue anymore (I would update to the latest babel (either 5 or 6).

If you have an an actual bug/suggestion for babel itself - free feel to make an issue on our [phabricator](https://phabricator.babeljs.io/). If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).

**Comment by GuoYongfeng** [comment]
好的，非常感谢，问题已经解决，是由于我们公司的npm镜像问题导致的，多谢回复。
