### ISSUE TITLE
babel-plugin-transform-strict-mode not working?

### ISSUE THREAD

**Issue by adamplabarge** [babel/gulp-babel#88]
I'm trying to remove the 'use strict'; that is added to the top of the javascript file that babel creates.  Either my /build/ or the .min.js.

I'm trying to remove it, can't figure out how. I have tried installing gulp plugins that say they remove 'use strict' but do not. I have tried adding the babel-plugin-transform-strict-mode plugin, and setting or adding to the babelrc config https://babeljs.io/docs/plugins/transform-strict-mode/ and setting to false.  If that even works.

How can I remove 'use strict'? It is driving me insane.

Link to the gulpfile.js
https://gist.github.com/adamplabarge/b7d890414c25bba7bf07f8eb70973d6d

Link to the package.json
https://gist.github.com/adamplabarge/3f43bfba9118bbf1292c8510678c4711

Link to the .babelrc
https://gist.github.com/adamplabarge/0b23dcb997ccff915de6b468c8ee8154

Could it be that one of the plugins is adding it?

**Comment by sindresorhus** [comment]
Use the proper support channels: https://github.com/babel/babel#looking-for-support :)
