### ISSUE TITLE
Invalid System.register call. Anonymous System.register calls can only be made by modules loaded by SystemJS.import and not via script tags.

### ISSUE THREAD

**Issue by ValeryIvanov** [babel/gulp-babel#90]
If I transpile with gulp-babel then I get error above.

If I transpile with babel-cli then its ok.

This is how it differs

This is transpiled with gulp-babel, this second System.register is causing this error.

	'use strict';

	System.register([], function (_export2, _context2) {
		return {
			setters: [],
			execute: function () {
				System.register(['jquery'], function (_export, _context) {
					var $;
					return {
						setters: [function (_jquery) {
							$ = _jquery.default;
						}],
						execute: function () {
						}
					};
				});
			}
		};
	});
	//# sourceMappingURL=validator.js.map

This is transpiled with babel-cli directly

	'use strict';

	System.register(['jquery'], function (_export, _context) {
		var $;
		return {
			setters: [function (_jquery) {
				$ = _jquery.default;
			}],
			execute: function () {
			}
		};
	});

**Comment by loganfsmyth** [comment]
Sounds like you've enabled the systemjs transform more than once. Do you happen to have it both in a. .babelrc and in your gulp task? If so, that would be why.

**Comment by ValeryIvanov** [comment]
This is my gulp task 

	var babel = require('gulp-babel');
	gulp.task('build:js', function() {
		return gulp.src(['lib/**/*.js', '!lib/templates.js'])
			.pipe(plumber())
			.pipe(changed(buildDirPath + '/js'))
			.pipe(sourcemaps.init())
			.pipe(babel())
			.pipe(sourcemaps.write('.'))
			.pipe(gulp.dest(buildDirPath + '/js'));
	});


this is my babelrc

	{
	  "presets": ["es2015", "stage-0", "react"],
	  "plugins": ["transform-es2015-modules-systemjs", "transform-flow-strip-types"]
	}


Does not seems so to my, since babel call should use babelrc file settings?

**Comment by ValeryIvanov** [comment]
Okay you were right, thanks for your help!

I was using jspm 0.17beta version with 'plugin-babel'. I removed 'transform-es2015-modules-systemjs' plugin and it worked.
