### ISSUE TITLE
'class' instead 'className'

### ISSUE THREAD

**Issue by mayantigo** [babel/gulp-babel#92]
Hello!.
```
Im using:
"babel-preset-es2015": "^6.9.0"
"gulp-babel": "^6.1.2",
"babel-preset-react": "^6.5.0",
"react": "^15.1.0"
```

And in gulpfile.json the follow:

```
gulp.src('./src/assets/react/*.jsx').pipe(babel({
		presets: ['react']
	})).pipe(gulp.dest('./src/assets/js'));
```

In my index.jsx I have: 

```
var Menu =  React.createClass({
  render: function() {
      return (
      	<ul class="myClass">
      		<li class="selected">Element</li>
      	</ul>
    );
  }
});

ReactDOM.render(React.createElement(Menu, null), document.getElementById('application'))
```

After use gulp-babel give me that code:

```
var Menu = React.createClass({
  displayName: "Menu",

  render: function () {
    return React.createElement(
      "ul",
      { "class": "myClass" },
      React.createElement(
        "li",
        { "class": "selected" },
        "Element"
      )
    );
  }
});

ReactDOM.render(React.createElement(Menu, null), document.getElementById('application'));
```

Generated html is:

`<ul data-reactroot=""><li>Element</li></ul>`

No classes in html code. Thing is if I change manually 'class' attribute for 'className', html code render 'class' attrbute correctly.

Im doing something wrong?. Do you know is if version conflict between react version and gulp-babel version?

Kind regards.

**Comment by mayantigo** [comment]
I tried with:

```
gulp.src('./src/assets/react/*.jsx').pipe(babel({
        presets: ['react', 'es2015']
    })).pipe(gulp.dest('./src/assets/js'));
```

And still same issue.

**Comment by loganfsmyth** [comment]
This is expected behavior, JSX does not always correspond directly with HTML. To get a `class` attribute, you'd use `className`, and to get a `for` attribute, you'd use `htmlFor`.

This behavior is documented on https://facebook.github.io/react/docs/jsx-in-depth.html.

**Comment by mayantigo** [comment]
Right, I missunderstood documentation. So stupid!
My apologize. Now works correctly.
Thanks for support!.

Kind regards.

**Comment by loganfsmyth** [comment]
No problem.
