### ISSUE TITLE
Unexpected character '?'

### ISSUE THREAD

**Issue by joSFD** [babel/gulp-babel#95]
Hi there !

I get this message :  Unexpected character '?' (22:1) on a directive which doesn't seem to have any problem (line 22 being the last line of the file) :

```
angular.module('app')
   .directive('backImg', backImg);

function backImg(){
    return {`
        restrict: 'A',`
        link: function(scope, element, attrs){
           element.addClass("ng-hide");
           var url = attrs.backImg;
           var image = new Image();
           image.src = url;
           image.onload = function(){
              element.css({'background-image': 'url(' + url + ')'});
              element.removeClass("ng-hide");
           }
       }
    }
 }​;
```

Any idea ?
Thank you !

Johan

**Comment by hzoo** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
