### ISSUE TITLE
how to disable the strict mode?

### ISSUE THREAD

**Issue by arixse** [babel/gulp-babel#97]
how to disable the strict mode?

**Comment by loganfsmyth** [comment]
@arixse The recommended approach would be to change your presets, e.g.

    presets: [
        'es2015'
    ]

to be

    presets: [
        ['es2015', {modules: false}]
    ]

note the new set of square brackets in there.

Babel code adds `use strict` automatically because `es2015` by default expects code to be ES6 modules, which are strict by default.

**Comment by cryoguy** [comment]
I am always getting following error.  Does it mean that it is still in strict mode?

Plumber found unhandled error:
 SyntaxError in plugin 'gulp-babel'
Message:
    /../app/scripts/prettyphoto/js/jquery.prettyPhoto.js: Deleting local variable in strict mode (7:21327):

my gulpjs setting:

gulp.task('scripts', () => {
  return gulp.src('app/scripts/**/*.js')
    .pipe($.plumber())
    .pipe($.sourcemaps.init())
    .pipe(babel({
            presets:[
		['es2015', {modules: false}]
	    ]
        }))
    .pipe($.sourcemaps.write('.'))
    .pipe(gulp.dest('.tmp/scripts'))
    .pipe(reload({stream: true}));
});

**Comment by hzoo** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).

**Comment by djwashburn** [comment]
Could you reopen this? I have the same problem as @cryoguy above - even with this setting, it fails on a complaint about deleting local variables in strict mode.

**Comment by ahmedofali** [comment]
Run this command :
```
 npm install --save-dev @babel/preset-es2015
```
then in the gulpfile add this 

```
presets: [
                ['@babel/preset-env', {modules: false}]
            ]
```

**Comment by sts-ryan-holton** [comment]
This isn't working, my JS is:

```js
gulp.task('build-plugin-js', () =>
  gulp.src([
    'src/js/plugin/script.js'
  ])
  .pipe(concat('les-inbound.js'))
  .pipe(babel({
    presets: ['@babel/preset-env', {modules: false}]
  }))
  .pipe(minify())
  .pipe(gulp.dest('public/dist/js/plugins/'))
);
```

**Comment by nicolo-ribaudo** [comment]
@sts-ryan-holton That's not enough to reproduce the error. Can you post the full stack trace, the input code and the generated code?

**Comment by maciej-gawlas** [comment]
@sts-ryan-holton try to add additional brackets :
`.pipe(babel({
    presets: [['@babel/preset-env', {modules: false}]]
  }))
`

**Comment by guilhermesantoss** [comment]
@maciej-gawlas thanks dude!
