### ISSUE TITLE
Use gulp-babel to transpile react project

### ISSUE THREAD

**Issue by GeorgeGkas** [babel/gulp-babel#98]
I want to transpile a react project. How to do it in gulp-babel? Do I have to use another module? I use es2015 and stage-0 presets. I saw in the examples how to convert es6 js files but what about react?

**Comment by rasenplanscher** [comment]
That's easy, have a look here: https://babeljs.io/docs/plugins/preset-react/

Just install the package `babel-preset-react`, and add `{ presets: ['react'] }` to your babel config

**Comment by hzoo** [comment]
Yep ^ is correct.

Closing this issue as it's been inactive for several months. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
