### ISSUE TITLE
gulp-babel Sourcemaps not working with TypeScript 2.0 via gulp-typescript

### ISSUE THREAD

**Issue by ijabit** [babel/gulp-babel#99]
When I use gulp-typescript to compile to ES6, then use Gulp-Babel after that (to go to ES5), it doesn't correctly apply the TypeScript sourcemap if the file is in a subdirectory. For example:
./src/tsfile1.ts <-- sourcemaps work great, through both gulp-typescript and gulp-babel
./src/subdir/tsfile2.ts <-- sourcemaps from gulp-typescript are broken, only the babel sourcemap gets applied

If found a workaround, if you modify the file.sourceMap.file property to use forward slashes instead of backslashes, the sourcemaps compile fine. This was a change in either the new gulp-typescript or TypeScript 2.0.3, not sure which, but now it uses backslashes on the file.sourceMap.file property.
Here is a straight dump of the sourceMap property on the vinyl file in both versions:
![image](https://cloud.githubusercontent.com/assets/557752/19371837/af4cac2c-9184-11e6-9e4d-2f26834a28eb.png)

Running this code on the file before it runs through gulp-babel fixes the issue temporarily:

```
if (file.sourceMap.file) {
    file.sourceMap.file = file.sourceMap.file.replace(/\\/g, '/');
}
```

Again, I'm not sure if the change in slashes comes from gulp-typescript or typescript v2, but either way gulp-babel should handle it I guess.

**Comment by ijabit** [comment]
Bump

**Comment by ijabit** [comment]
There was a fix for gulp-typescript, but I still think that gulp-babel should handle backslashes correctly when generating source maps.
Thanks

**Comment by hzoo** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
